### ISSUE TITLE
WARNING

### ISSUE THREAD

**Issue by KnifeBoss** [gabamnml/hoper#2]
Hello, I get this error when typing `gem install hoper`:

`WARNING:  You don't have /home/g/.gem/ruby/2.4.0/bin in your PATH,
	  gem executables will not run.
Successfully installed hoper-0.1.0
Parsing documentation for hoper-0.1.0
Done installing documentation for hoper after 0 seconds
1 gem installed
`

How do i fix the warning?

**Comment by gabamnml** [comment]
You can try with:

export PATH=$PATH':/home/g/.gem/ruby/2.4.0/bin'
export GEM_HOME=$HOME/.gem
export GEM_PATH=$HOME/.gem
